-- Create the table
create table restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  lat double precision not null,
  lng double precision not null,
  discount text,
  image text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Turn on Row Level Security
alter table restaurants enable row level security;

-- Create a policy that allows anyone to read
create policy "Public restaurants are viewable by everyone."
  on restaurants for select
  using ( true );

-- Insert default data (matching our mock)
insert into restaurants (name, category, lat, lng, discount, image, description)
values
  ('La Pampa', 'Parrillada Premium', -38.7415, -72.6176, '20% en Cortes Premium', 'https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?q=80&w=800&auto=format&fit=crop', 'La mejor carne a las brasas de Temuco. Experiencia única en cortes seleccionados.'),
  ('Marriet', 'Cocina de Autor', -38.7390, -72.6000, 'Postre Gratis', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=800&auto=format&fit=crop', 'Cocina sofisticada, ambiente exclusivo y una carta de vinos insuperable.'),
  ('Confitería Central', 'Café & Pastelería', -38.7350, -72.5900, '2x1 en Café de Grano', 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=800&auto=format&fit=crop', 'Tradición alemana en el corazón de la ciudad. Pastelería fresca cada día.'),
  ('Beers N Burgers', 'Hamburguesas', -38.7320, -72.6200, '15% Off Total Cuenta', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop', 'Hamburguesas artesanales gigantes y la mejor selección de cervezas locales.'),
  ('Mercado Municipal', 'Cocina Típica Chilena', -38.7300, -72.5850, 'Menú Ejecutivo $5.990', 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=800&auto=format&fit=crop', 'Sabores tradicionales de la Araucanía. Cazuelas, pastel de choclo y más.');
